### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by HilmiK** [dvornikita/context_aug#2]
I got the following error at the inference stage:

FileNotFoundError: [Errno 2] No such file or directory:  /path/to/context_aug/Data/context_probs/voc12train_neg3-voc12val_small-1neib/2007_000033.npy'

After training, there is no .npy file appearing in my directories, so this is the reason but I could not understand which part I am missing ?

Thanks.

**Comment by dvornikita** [comment]
Those are the files you are obtaining after the trained model inference. Did you run the trained model on the VOC07 already?

**Comment by HilmiK** [comment]
I trained the model and obtained ckpt files with 10k iterations. And, at the context model inference step when I apply :  

python3 $ROOT/Scripts/encode_context.py --run_name=voc12train_neg3 --dataset=voc12 --split=val --small_data --ckpt=10

It says --ckpt is unrecognized arguments and that is my another issue.

After removing --ckpt argument, it gives this error.

By the way, VOC07 is not used in any step, the code is working with VOC2012 I thought?

**Comment by dvornikita** [comment]
My bad, I'm sorry. There was a typo in the readme. You need to run $ROOT/inference.py file with those arguments. 
I updated the Readme accordingly.
Thanks for the error found. Feel free to write if you have any other issues.

**Comment by HilmiK** [comment]
Oh, thanks a lot.
