### ISSUE TITLE
Some questions about the training process of the network

### ISSUE THREAD

**Issue by yudawen** [dvornikita/context_aug#5]
Hello！The parameter “image_size：which image size to chose for training” in config.py is mean to scale the image by "image_size" and then crop the box containing the target,I don't understand its meaning.Can you explain the whole process to me about training the Context Model, for example, after inputting the image, crop the target according to the annotation information, and then send them to the classification network? So the "batch_size” in config.py is  the number of objects containing the background?

**Comment by dvornikita** [comment]
Hey,

Sorry for the late response. The process of training the context model is well explained in the original paper. 
The parameter batch_size is the total number of images that go through the networks on one training iteration, so both images that contain an object and the ones of background.

If you still have questions ill be glad to answer.

Best,
Nikita

**Comment by hejiyan** [comment]
Thanks! I have got it by reading your original paper.

**Comment by yudawen** [comment]
Thanks! I have got it by reading your original paper.

**Comment by hejiyan** [comment]
x, y, w, h = box
        # sampling w, h parameters of a frame
        min_area = self.min_context_area + w*h    # since the box will be cut out
        fw = np.random.uniform(max(w, min_area), 1)
        fh = np.random.uniform(max(h, min_area / fw), 1)

        # sampling x, y parameters of a frame
        img_size_constr_right = np.minimum(1 - np.array([fw, fh]), np.array([x, y]))
        obj_box_constr_left = np.array([x + w - fw, y + h - fh]).clip(0, 1)
        fx = np.random.uniform(obj_box_constr_left[0], img_size_constr_right[0])
        fy = np.random.uniform(obj_box_constr_left[1], img_size_constr_right[1])
        return box, np.array([fx, fy, fw, fh])

Can you tell me about the role of this part?
